global:
  scrape_interval: 10s
  evaluation_interval: 10s

#scrape_configs:
#  - job_name: 'otel-collector'
#    static_configs:
#      - targets: ['otel-collector:8889']

scrape_configs:
  - job_name: 'order-service.app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']