
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productservice
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect