
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productservice
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never