version: '3'
services:
  prometheus:
    container_name: orderservice-prometheus
    image: prom/prometheus
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "7070:7070"

  grafana:
    container_name: orderservice-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"