version: '3'
services:
  product-service:
    build: ./
    environment:
      OTEL_TRACES_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: productservice
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"