version: '3'
services:
  product-service:
    image: productservice:0.0.2-SNAPSHOT
    environment:
      OTEL_SERVICE_NAME: "product-service"
      OTEL_TRACES_EXPORTER: "jaeger,zipkin"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - jaeger
      - zipkin

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OLTP_ENABLED=true
    restart: always
    ports:
      - "16686:16686"
      - "14250"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: productservice
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"